[package]
name = "geyser-test-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
solana-geyser-plugin-interface = "1.18.23"
solana-logger = { version = "2.0.8" }
log = "0.4.14"
serde = { version = "1.0.204", features = ["derive"] }
thiserror = "1.0.63"
crossbeam-channel = "0.5.13"
