[package]
name = "geyser-test-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
solana-geyser-plugin-interface = "1.18.18"
solana-sdk = "~1.18.16"
solana-program = "~1.18.16"
solana-transaction-status = "~1.18.16"

solana-logger = { version = "2.0.8" }
log = "0.4.14"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.63"
crossbeam-channel = "0.5.13"
tokio = { version = "1.40.0", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["full"] }
tokio-tungstenite = { version = "0.23.1" }
futures-util = "0.3.3"
